sudo: false
cache:
  directories:
    - $TRAVIS_BUILD_DIR/data
branches:
  only:
    - master
    - stable
language: python
python:
  - "2.7"
  - "3.4"
env:
  - TESTS=fuel
  - TESTS=blocks
before_install:
  # Setup Python environment with BLAS libraries
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update -q --yes conda
  - export FUEL_DATA_PATH=$TRAVIS_BUILD_DIR/data
install:
  # Install all Python dependencies
  - |
      if [[ $TESTS == 'blocks' ]]; then
        curl -O https://raw.githubusercontent.com/mila-udem/blocks/$TRAVIS_BRANCH/req-travis-conda.txt
        conda install -q --yes python=$TRAVIS_PYTHON_VERSION --file req-travis-conda.txt
        pip install -r https://raw.githubusercontent.com/mila-udem/blocks/$TRAVIS_BRANCH/req-travis-pip.txt
        pip install -e git+git://github.com/mila-udem/blocks.git@$TRAVIS_BRANCH#egg=blocks --src=$HOME -r https://raw.githubusercontent.com/mila-udem/blocks/$TRAVIS_BRANCH/requirements.txt
      fi
  - |
      if [[ $TESTS == 'fuel' ]]; then
        conda install -q --yes python=$TRAVIS_PYTHON_VERSION --file req-travis-conda.txt
        pip install -r req-travis-pip.txt
        pip install . -r requirements.txt # Installs the fuel-download command needed by .travis-data.sh
        python setup.py build_ext --inplace
      fi
script:
  - ./.travis-data.sh adult mnist binarized_mnist "caltech101_silhouettes 16" cifar10 cifar100 iris ilsvrc2010
  - function fail { export FAILED=1; }
  - |
      if [[ $TESTS == 'blocks' ]]; then
        bokeh-server &> /dev/null &
        nose2 tests --start-dir $HOME/blocks || fail
        nose2 doctests --start-dir $HOME/blocks || fail
        return $FAILED
      fi
  - |
      if [[ $TESTS == 'fuel' ]]; then
        # Running nose2 within coverage makes imports count towards coverage
        coverage run -p --source=fuel -m nose2.__main__ -v tests || fail
        coverage run -p --source=fuel -m nose2.__main__ -v doctests || fail
        return $FAILED
      fi
after_script:
  - |
      if [[ $TESTS == 'fuel' ]]; then
        coverage combine
        coveralls
      fi
